### ISSUE TITLE
WebGl Test Patcher is making issues while making build

### ISSUE THREAD

**Issue by usama25** [MrVeit/Veittech-UnitonConnect#13]
WebGl Thread Patcher is making issues while making build. And if we don't use it, then the callbacks throws error in uniton sdks.
Here is the error i am getting while making build:

D:\6000.0.25f1\Editor\Data\il2cpp\build\deploy\il2cpp.exe @Library\Bee\artifacts\rsp\13183207201333623782.rsp
Error: IL2CPP error for method 'System.Void System.Threading.<>_GenericWrapper::.ctor(System.Action1<T>)' in assembly 'E:\Unity\Projects\Git\FluffyFox-Unity\Library\Bee\artifacts\WebGL\ManagedStripped\mscorlib.dll'
System.InvalidOperationException: Attempting to return from void method 'System.Void System.Threading.<>_GenericWrapper::.ctor(System.Action1<T>)' when there are values on the stack. Is this invalid IL code?
   at Unity.IL2CPP.MethodBodyWriter.WriteReturnStatement() + 0x4ea
   at Unity.IL2CPP.MethodBodyWriter.ProcessInstruction(Node, InstructionBlock, ResolvedInstruction) + 0x85e
   at Unity.IL2CPP.MethodBodyWriter.GenerateCodeRecursive(Node, ReadOnlyDictionary2) + 0x827
   at Unity.IL2CPP.MethodBodyWriter.Generate() + 0x72f
   at Unity.IL2CPP.CodeWriters.CodeWriterExtensions.WriteMethodWithMetadataInitialization(IGeneratedMethodCodeWriter, String, Action2, String, MethodReference, WritingMethodFor) + 0x2ef

**Comment by MrVeit** [comment]
Hello, I am aware of this issue and it is relevant for Unity 2023+ and above.
If you are using version 0.2.9.5 with native window, you can safely remove this plugin patcher and use UniTask in those asynchronous SDK methods that are relevant for you in the project.

In a few versions, when support for the past .NET implementation will be discontinued and only native will remain, the implementation of asynchronous methods will completely switch to UniTask.

**Comment by MrVeit** [comment]
To fully initialize the SDK with the new implementation only, then you can comment out these lines in the `Initialize()` method inside the main `UnitonConnectSDK` script.

Since they only use Task in the .NET implementation, you probably have an initialization problem.

![image](https://github.com/user-attachments/assets/f4088c39-6b10-4ce4-89a7-f85c526fba71)

**Comment by usama25** [comment]
Hey Nickolay! Thanks for the reply. This is a really important project on
which I am working. If I lose this project I will lose my job. kindly bare
with me.

So actually if I don't use webgl thread patcher I am getting errors during
fetching balance or making transactions. What I have done is made an empty
project in unity 6 . Added ton connect sdk. Then added your uniton package
. Did necessary configurations like app urls and made a build of your
sample scene.
The wallet connection is working good . But when I press send ton button I
get "mismatch or null function call" error in my browser . Same when I try
to send ton .
I am assuming this is because unity is not being able to fetch the
functions from jslib. And the issue is due to webgl thread patcher please
guide me on this

And unity 6 is necessary because client needs to remove the unity splash
screen

**Comment by MrVeit** [comment]
What version of Uniton Connect are you using?

The latest version has native connection via Ton Connect UI and since everything happens on promises via Java Script, the Web GL patcher is not needed there.

I'll test this theory now and let you know, expect a reply within the hour!

**Comment by MrVeit** [comment]
Yes, it works as it should without this patcher on the native version of the SDK.
I'm going to build a .unityPackage version and submit it here, you can find a guide on how to migrate from .NET implementation to native here:
https://github.com/MrVeit/Veittech-UnitonConnect/blob/main/Docs/MigrationToNativeSDKGuide.MD

P.S: If you are using an older version of Uniton Connect, uninstall it and install the latest version of unityPackage from the release branch:
https://github.com/MrVeit/Veittech-UnitonConnect/releases/tag/0.2.9.6

**Comment by usama25** [comment]
I am already using the latest one 0.2.9.6 . And also i am using your sample scene and didn't touch the code. when i make build the wallet connection is working fine but when i click on send ton I am getting this error : 
3176c3fc-9735-4ccd-ac48-475e63a52f2b:9 Uncaught RuntimeError: null function or function signature mismatch
    at 0f071f76:0x342787b
    at invoke_iii (3176c3fc-9735-4ccd-a…5e63a52f2b:9:490389)
    at 0f071f76:0x127e50a
    at 0f071f76:0x258c85c
    at 0f071f76:0x29443b9
    at 0f071f76:0x296b2ad
    at 0f071f76:0x342784e
    at invoke_iiii (3176c3fc-9735-4ccd-a…5e63a52f2b:9:490715)
    at 0f071f76:0x296a28a
    at 0f071f76:0x16a500
    at 0f071f76:0x3380a63
    at 0f071f76:0x333dddc
    at 0f071f76:0x3333840
    at 0f071f76:0x33a9c33
    at 0f071f76:0x25911fb
    at 0f071f76:0x2591153
    at 0f071f76:0x1283247
    at 0f071f76:0x1288a40
    at 0f071f76:0x2902dcc
    at 0f071f76:0x296b2ad
    at 0f071f76:0x342784e
    at invoke_iiii (3176c3fc-9735-4ccd-a…5e63a52f2b:9:490715)
    at 0f071f76:0x296a28a
    at 0f071f76:0x16a500
    at 0f071f76:0x3380a63
    at 0f071f76:0x333472c
    at 0f071f76:0x3090668
    at 0f071f76:0x333404b
    at 0f071f76:0x33409e3
    at 0f071f76:0x334089c
    at 0f071f76:0x33598b2
    at 0f071f76:0x3359948
    at 0f071f76:0x33a911f
    at 0f071f76:0x258ed69
    at 0f071f76:0x12889d9
    at 0f071f76:0x128870d
    at 0f071f76:0x259fec0
    at 0f071f76:0x84a258
    at 0f071f76:0x11deccc
    at 0f071f76:0x364af2
    at 0f071f76:0x34278ff
    at invoke_viiii (3176c3fc-9735-4ccd-a…5e63a52f2b:9:491498)
    at 0f071f76:0x1b1ca98
    at 0f071f76:0x11e2e50
    at 0f071f76:0x11e48d8
    at 0f071f76:0x11e3723
    at 0f071f76:0x11e33df
    at 0f071f76:0x11de14b
    at 0f071f76:0x2902dcc
    at 0f071f76:0x296b2ad
![Screenshot 2024-11-25 034321](https://github.com/user-attachments/assets/6ffec62d-93e0-496a-a7d8-27372649405d)

**Comment by MrVeit** [comment]
Can you share the link?
I will look at the logs in detail.

**Comment by usama25** [comment]
Here is the bot link:
https://web.telegram.org/k/#@Fluffyfox_devBot

**Comment by MrVeit** [comment]
This is already a problem with Unity 6, not the SDK.

I will try to address support for this version in future releases.

Unfortunately, you will have to drop the project down to version 2022, as these methods and below work fine there as well.
Apparently they removed this functionality for builds in the version 6 release, we will need to look into this further. Thanks for bringing this to my attention, as I am using Unity version 2022 and below.

There is a way to remove Unity Splash Screen to version 6. You just need to put the script from here anywhere in the project and everything will work perfectly in that regard:
https://github.com/Jadekylin/UnitySkipSplash/blob/main/SkipSplash.cs

![image](https://github.com/user-attachments/assets/e3d38c8e-f00a-4521-a57b-a84faa28562e)

**Comment by usama25** [comment]
Thankyou so much for your time and efforts. I will be looking forward for the future releases solving this issue. 
Thanks again for the splash remover script

**Comment by MrVeit** [comment]
Glad to be of help, thanks for using the Uniton Connect SDK 🤝

**Comment by usama25** [comment]
okay got it. thanks

**Comment by MrVeit** [comment]
I don't know myself yet, there's only digging for info and figuring it out, so sorry :0
